version: '3.1'
services:
  jenkins:
    build:
      context: ./master
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    image: jenkins
  jenkins-agent:
    build:
      context: ./agent
    container_name: jenkins-agent
    restart: always
    environment:
      - 'JENKINS_URL=http://jenkins:8080'
    image: jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins